// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiGdZ_n5i1bnvhLhpsWaC7gnnebZ1mGz8',
    appId: '1:622123599266:web:e486638e6bfa342d18defb',
    messagingSenderId: '622123599266',
    projectId: 'flutter-varios-3d5dd',
    authDomain: 'flutter-varios-3d5dd.firebaseapp.com',
    databaseURL: 'https://flutter-varios-3d5dd-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-varios-3d5dd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIK09MNCA74aoaQDsPFnaGVs6Gxaql4bQ',
    appId: '1:622123599266:android:32fab434583eab2018defb',
    messagingSenderId: '622123599266',
    projectId: 'flutter-varios-3d5dd',
    databaseURL: 'https://flutter-varios-3d5dd-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-varios-3d5dd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAp5R-kUmTa7TZhcFC1A0EL74XYdk_-XXI',
    appId: '1:622123599266:ios:be9fc53655710f7718defb',
    messagingSenderId: '622123599266',
    projectId: 'flutter-varios-3d5dd',
    databaseURL: 'https://flutter-varios-3d5dd-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-varios-3d5dd.appspot.com',
    iosBundleId: 'com.example.flNotificaciones',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAp5R-kUmTa7TZhcFC1A0EL74XYdk_-XXI',
    appId: '1:622123599266:ios:be9fc53655710f7718defb',
    messagingSenderId: '622123599266',
    projectId: 'flutter-varios-3d5dd',
    databaseURL: 'https://flutter-varios-3d5dd-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-varios-3d5dd.appspot.com',
    iosBundleId: 'com.example.flNotificaciones',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAiGdZ_n5i1bnvhLhpsWaC7gnnebZ1mGz8',
    appId: '1:622123599266:web:b9cd43cc6d6d0f7718defb',
    messagingSenderId: '622123599266',
    projectId: 'flutter-varios-3d5dd',
    authDomain: 'flutter-varios-3d5dd.firebaseapp.com',
    databaseURL: 'https://flutter-varios-3d5dd-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-varios-3d5dd.appspot.com',
  );
}
